# Generated by Django 3.0.3 on 2020-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200802_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
